// GameRegistry — single source of truth for every game in the hub.
// Adding a game: drop games/<id>/game.js, add one entry here, and (optionally)
// a cover scene in Art.js. Everything else picks it up automatically.

export const CATEGORIES = ["Puzzle", "Arcade", "Board", "Casual"];

export const GAMES = [
  // ---------------- Puzzle ----------------
  { id: "merge2048", title: "Number Merge", category: "Puzzle", difficulty: "Medium", colors: ["#ffb347", "#ff5e62"],
    description: "Slide and merge glowing tiles to reach 2048.",
    how: "Swipe or use the arrow keys to slide every tile. Two equal tiles merge into one — keep merging to build 2048.", controls: ["← ↑ → ↓", "Swipe"] },
  { id: "memorymatch", title: "Memory Match", category: "Puzzle", difficulty: "Easy", colors: ["#a18cd1", "#6a3de8"],
    description: "Flip cards and find every matching pair.",
    how: "Flip two cards at a time. Find all the pairs with as few moves as possible — faster clears score more.", controls: ["Click / Tap"] },
  { id: "slidingpuzzle", title: "Sliding Puzzle", category: "Puzzle", difficulty: "Medium", colors: ["#43cea2", "#185a9d"],
    description: "Slide the tiles back into order.",
    how: "Click a tile next to the gap (or use arrow keys) to slide it. Put 1–15 back in order in the fewest moves.", controls: ["Click", "← ↑ → ↓"] },
  { id: "minesweeper", title: "Mine Finder", category: "Puzzle", difficulty: "Hard", colors: ["#56ccf2", "#2f80ed"],
    description: "Clear the field without hitting a mine.",
    how: "Reveal safe cells. Numbers tell you how many mines touch that cell. Right-click or long-press to plant a flag.", controls: ["Click", "Right-click = flag"] },
  { id: "bubblepop", title: "Bubble Pop", category: "Puzzle", difficulty: "Easy", colors: ["#f093fb", "#f5576c"],
    description: "Pop groups of 2+ same-color bubbles.",
    how: "Tap a group of two or more touching bubbles of the same color. Bigger groups score way more. Clear the board for a bonus!", controls: ["Click / Tap"] },
  { id: "patternmemory", title: "Pattern Memory", category: "Puzzle", difficulty: "Medium", colors: ["#fa709a", "#7b4397"],
    description: "Repeat the growing light-and-sound sequence.",
    how: "Watch the pads light up, then repeat the sequence. Each round adds one more step.", controls: ["Click / Tap", "Keys 1–4"] },
  { id: "colormatch", title: "Color Match", category: "Puzzle", difficulty: "Easy", colors: ["#f6d365", "#fda085"],
    description: "Spot the one tile with a different shade.",
    how: "One tile is a slightly different shade. Find it before time runs out — it gets harder every level.", controls: ["Click / Tap"] },
  { id: "wordscramble", title: "Word Puzzle", category: "Puzzle", difficulty: "Medium", typing: true, colors: ["#f7971e", "#c0392b"],
    description: "Unscramble the letters to find the word.",
    how: "Tap letters (or type) to spell the hidden word. Use a hint if you're stuck — but it costs points.", controls: ["Type", "Click", "Enter"] },
  { id: "blockdrop", title: "Block Drop", category: "Puzzle", difficulty: "Medium", colors: ["#00c6ff", "#0072ff"], isNew: true,
    description: "Rotate falling blocks and clear full lines.",
    how: "Move and rotate the falling pieces to complete horizontal lines. Clear several lines at once for big combos.", controls: ["← →", "↑ rotate", "↓ soft", "Space drop"] },
  { id: "jewelswap", title: "Jewel Swap", category: "Puzzle", difficulty: "Medium", colors: ["#ff6fd8", "#3813c2"], isNew: true,
    description: "Swap gems to match 3 and trigger cascades.",
    how: "Swap two neighboring gems to line up 3 or more of a kind. Chain cascades before the timer runs out.", controls: ["Click two gems", "Drag"] },
  { id: "sudoku", title: "Sudoku", category: "Puzzle", difficulty: "Hard", colors: ["#667eea", "#3b2a8f"], isNew: true,
    description: "Fill the grid so every row, column and box has 1–9.",
    how: "Select a cell and enter a number. Each row, column and 3×3 box must contain 1–9 exactly once. 3 mistakes and it's over.", controls: ["Click", "1–9", "Arrows"] },

  // ---------------- Arcade ----------------
  { id: "snake", title: "Circuit Snake", category: "Arcade", difficulty: "Medium", colors: ["#56ab2f", "#0f5132"],
    description: "Eat, grow, and don't bite yourself.",
    how: "Steer the neon snake to eat energy orbs. Every orb makes you longer and faster. Don't hit the walls or yourself!", controls: ["← ↑ → ↓", "WASD", "Swipe"] },
  { id: "brickbreaker", title: "Brick Breaker", category: "Arcade", difficulty: "Medium", colors: ["#ff512f", "#dd2476"],
    description: "Smash every brick with the bouncing ball.",
    how: "Move the paddle to keep the ball in play and break all the bricks. Catch falling power-ups for wide paddle or multi-ball.", controls: ["Mouse / Touch", "← →", "Space launch"] },
  { id: "skyhopper", title: "Sky Hopper", category: "Arcade", difficulty: "Hard", colors: ["#4facfe", "#00f2fe"],
    description: "Flap through the gaps between the pillars.",
    how: "Tap, click or press Space to flap. Fly through the gaps — every pillar you pass is a point.", controls: ["Space", "Click / Tap"] },
  { id: "spaceshooter", title: "Star Defender", category: "Arcade", difficulty: "Medium", colors: ["#141e30", "#6a3de8"],
    description: "Blast asteroids and alien drones.",
    how: "Move your ship and blast everything. Collect power cores for triple shot. Survive as long as you can.", controls: ["← → / Mouse", "Auto-fire"] },
  { id: "dodgerunner", title: "Dodge Runner", category: "Arcade", difficulty: "Medium", colors: ["#fc466b", "#3f5efb"],
    description: "Switch lanes on the neon highway.",
    how: "Race down the neon road and switch lanes to dodge traffic. Grab coins for bonus points. It keeps getting faster.", controls: ["← →", "Swipe / Tap sides"] },
  { id: "coincollector", title: "Coin Collector", category: "Arcade", difficulty: "Easy", colors: ["#f7b733", "#fc4a1a"],
    description: "Grab the coins, dodge the bombs.",
    how: "Move around the arena to grab coins before they vanish. Avoid the rolling bombs — you have 3 lives.", controls: ["Arrows / WASD", "Mouse / Touch"] },
  { id: "stacktower", title: "Stack Tower", category: "Arcade", difficulty: "Easy", colors: ["#ee9ca7", "#6f3fd1"], isNew: true,
    description: "Drop sliding blocks to build the tallest tower.",
    how: "Tap to drop the sliding block. Anything that overhangs gets sliced off. Perfect drops keep your block full size!", controls: ["Space", "Click / Tap"] },
  { id: "cloudjumper", title: "Cloud Jumper", category: "Arcade", difficulty: "Medium", colors: ["#89f7fe", "#66a6ff"], isNew: true,
    description: "Bounce up the clouds as high as you can.",
    how: "Steer left and right — you bounce automatically. Springs launch you higher, and breaking clouds crumble. Don't fall!", controls: ["← →", "Mouse / Tilt"] },
  { id: "neonpong", title: "Neon Pong", category: "Arcade", difficulty: "Medium", colors: ["#0f0c29", "#e0409b"], isNew: true,
    description: "Classic paddle duel against the computer.",
    how: "Move your paddle to return the ball. First to 7 points wins. The ball speeds up on every hit.", controls: ["Mouse / Touch", "↑ ↓ / W S"] },

  // ---------------- Board ----------------
  { id: "tictactoe", title: "Tic Tac Toe", category: "Board", difficulty: "Easy", colors: ["#8e2de2", "#4a00e0"],
    description: "Classic 3×3 vs the computer or a friend.",
    how: "Get three in a row. Play against the computer (it's smart!) or pass-and-play with a friend.", controls: ["Click / Tap"] },
  { id: "connectfour", title: "Four in a Row", category: "Board", difficulty: "Medium", colors: ["#2193b0", "#1c3f94"],
    description: "Drop discs and connect four first.",
    how: "Drop discs into columns. First to line up four — horizontally, vertically or diagonally — wins.", controls: ["Click column", "1–7"] },
  { id: "dotsandboxes", title: "Dots & Boxes", category: "Board", difficulty: "Medium", colors: ["#ff9966", "#c2185b"],
    description: "Draw lines and claim the most boxes.",
    how: "Take turns drawing lines. Complete the 4th side of a box to claim it and move again. Play the computer or a friend.", controls: ["Click lines"] },
  { id: "reversi", title: "Reversi", category: "Board", difficulty: "Medium", colors: ["#11998e", "#0b5d3b"], isNew: true,
    description: "Outflank and flip your opponent's discs.",
    how: "Place a disc to trap computer discs in a line between yours — they flip to your color. Most discs at the end wins.", controls: ["Click / Tap"] },

  // ---------------- Casual ----------------
  { id: "quickmath", title: "Quick Math", category: "Casual", difficulty: "Easy", colors: ["#00b09b", "#096c5e"],
    description: "Solve equations against the clock.",
    how: "Pick the right answer as fast as you can. Streaks multiply your points and add time.", controls: ["Click", "Keys 1–4"] },
  { id: "reactiontest", title: "Reaction Test", category: "Casual", difficulty: "Easy", colors: ["#e53935", "#6d1b1b"],
    description: "Tap the instant the screen turns green.",
    how: "Wait for green, then tap as fast as you can. Five rounds — faster reactions mean a higher score. Don't jump the gun!", controls: ["Click / Tap", "Space"] },
  { id: "targettap", title: "Target Tap", category: "Casual", difficulty: "Easy", colors: ["#ff416c", "#ff4b2b"],
    description: "Hit the shrinking targets before they vanish.",
    how: "Tap targets before they shrink away. Hit the bullseye for extra points. 30 seconds on the clock.", controls: ["Click / Tap"] },
  { id: "fruitcatch", title: "Fruit Catch", category: "Casual", difficulty: "Easy", colors: ["#a8e063", "#2e8b3a"],
    description: "Catch falling fruit, avoid the bombs.",
    how: "Move the basket to catch fruit. Golden stars are worth extra. Miss 3 fruits or catch a bomb and you lose a life.", controls: ["Mouse / Touch", "← →"] },
  { id: "molebash", title: "Mole Bash", category: "Casual", difficulty: "Easy", colors: ["#c79081", "#5a3a22"], isNew: true,
    description: "Bonk the moles as they pop up.",
    how: "Whack moles as they pop out of their holes. Golden moles are worth triple — but don't hit the bunnies!", controls: ["Click / Tap", "Keys 1–9"] },
  { id: "typingrush", title: "Typing Rush", category: "Casual", difficulty: "Medium", typing: true, colors: ["#4776e6", "#8e54e9"], isNew: true,
    description: "Type the falling words before they land.",
    how: "Type the falling words to destroy them. Don't let any reach the ground — you have 3 shields.", controls: ["Keyboard"] },
  { id: "minigolf", title: "Mini Golf", category: "Casual", difficulty: "Easy", colors: ["#56ab2f", "#a8e063"], isNew: true,
    description: "Sink the ball in 9 quirky holes.",
    how: "Drag back from the ball to aim, release to putt. Fewer strokes = more points. Watch out for walls and water!", controls: ["Drag & release"] }
];

export function getGame(id) { return GAMES.find((g) => g.id === id); }
